apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zpenv-configmap
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  {{- range $key, $val := .Values.noteBookStorage }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  {{- range $key, $val := .Values.sparkEventLog }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
---
{{- if (not .Values.global.umbrellaChart) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zeppelin-configmap
data:
{{ (.Files.Glob "conf/zeppelin/*").AsConfig | indent 2 }}
{{- end }}
---
{{- if (not .Values.global.umbrellaChart) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zpspark-configmap
data:
{{ (.Files.Glob "conf/spark/*").AsConfig | indent 2 }}
{{- end }}
---
{{- if and .Values.mountSecrets (not .Values.global.umbrellaChart) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-zp-secrets
type: Opaque
data:
{{ (.Files.Glob "conf/secrets/*").AsSecrets | indent 2 }}
{{- end }}