apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: mysql-gluster 
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.244.3.7:8080"
  restuser: "mysql"
  restuserkey: "mysql123"
