kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-hs-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: snappydata
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

