#############################
# Specific to PCF tile
#############################
locators:
  resources:
    requests:
      memory: 1024Mi
  persistence:
    size: 10Gi

servers:
  replicaCount: 2
  resources:
    requests:
      memory: 4096Mi
  persistence:
    size: 20Gi

leaders:
  resources:
    requests:
      memory: 4096Mi
  persistence:
    size: 20Gi