apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hsenv-configmap
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.historyServerConf }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- if and .Values.mountSecrets (not .Values.global.umbrellaChart) }}
apiVersion: v1
kind: Secret
metadata:
  name: history-secrets
type: Opaque
data:
{{ (.Files.Glob "conf/secrets/*").AsSecrets | indent 2 }}
{{- end }}