kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
   name: strimzi-io-priority-high
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  snap_interval:   "70"
  io_priority:  "high"
