apiVersion: v1
appVersion: "1.0"
description: A Helm chart to deploy Spark history server for Kubernetes
name: spark-hs
version: 0.1.0
home: https://github.com/apache-spark-on-k8s/spark
icon: http://spark.apache.org/images/spark-logo-trademark.png
maintainers:
  - name:
    email:

