# This is not a recommended configuration, and further support should be available
# from the Prometheus and Grafana communities

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]