apiVersion: v1
appVersion: "1.0"
description: A Helm chart for launching Jupyter notebooks with Apache Spark in-cluster client mode.
name: jupyter-with-spark
version: 0.1.0
home: https://github.com/apache-spark-on-k8s/spark
icon: http://spark.apache.org/images/spark-logo-trademark.png
maintainers:
  - name: SnappyData, Inc.
    email: chomp@snappydata.io
