# Default values for spark-shuffle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: snappydatainc
  tag: spark-shuffle:v2.2.0-kubernetes-0.5.1
  pullPolicy: IfNotPresent

shufflePodLabels:
  app: spark-shuffle-service
  spark-version: 2.2.0

serviceAccount: default

resources:
  limits:
    cpu: 200m
  #  memory: 128Mi
  requests:
    cpu: 200m
  #  memory: 128Mi

#internal attribute, do not change
global:
  umbrellaChart: false