apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jupyter-spark
  labels:
    app: {{ template "jupyter-with-spark.name" . }}
    chart: {{ template "jupyter-with-spark.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.jupyterService.type | default "LoadBalancer" | quote }}
  ports:
    - port: {{ .Values.jupyterService.jupyterPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.jupyterService.sparkUIPort }}
      targetPort: web-ui
      protocol: TCP
      name: web-ui
  selector:
    app: {{ template "jupyter-with-spark.name" . }}
    release: {{ .Release.Name }}
---
