apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rss-configmap
data:
  resource-staging-server.properties: |
    spark.kubernetes.resourceStagingServer.port={{ .Values.service.internalPort }}
    {{- range $key, $val := .Values.properties }}
    {{ $key }}={{ $val }}
    {{- end}}