apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark-rss.fullname" . }}
  labels:
    app: {{ template "spark-rss.name" . }}
    chart: {{ template "spark-rss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" -}}
      nodePort: {{ .Values.service.nodePort }}
      {{ end -}}
      name: rssport
  selector:
    app: {{ template "spark-rss.name" . }}
    release: {{ .Release.Name }}
#   TODO: Is this required
    resource-staging-server-instance: default